# Generated by Django 5.1 on 2024-08-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_fooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
